### ISSUE TITLE
[QA - Front] Bug found - Redirect pós login

### ISSUE THREAD

**Issue by EduCR03** [S204-Inatel-2023-2/binaryhorizon_eventhis_front#14]
Quando o usuario realiza o cadastro a pagina de perfil nao atualiza para o perfil, ou para a tela de login

**Comment by airtong** [comment]
Bom dia @EduCR03.

Subi a alteração:
https://github.com/S204-Inatel-2023-2/binaryhorizon_eventhis_front/pull/17

Assim que o @LucasSResende aprovar, estará na master.

Favor, assim que possível, fazer uma avaliação.

Caso esteja resolvido, favor fechar a issue.

**Comment by airtong** [comment]
Já está na https://github.com/S204-Inatel-2023-2/binaryhorizon_eventhis_front/tree/main

**Comment by lrgsouza** [comment]
@EduCR03 bug corrigido, favor realizar testes e fechar card.

**Comment by airtong** [comment]
Outro bug que estava ocorrendo:
Dados do usuário que deslogou mantidos ao acessar o profile.

Agora os dados carregados estão sempre atualizados: https://github.com/S204-Inatel-2023-2/binaryhorizon_eventhis_front/pull/26.

**Comment by lrgsouza** [comment]
Fechando o card devido ao report do @LucasSResende nos testes de interface.
