### ISSUE TITLE
[FRONT-END] Definição de temas claro/escuro

### ISSUE THREAD

**Issue by lrgsouza** [S204-Inatel-2023-2/binaryhorizon_eventhis_front#15]
Temas claro e escuro já estão funcionando.
Definir cabeçalho da página com cor estática e manter logotipo branco.

**Comment by airtong** [comment]
Sugestão de alteração:

Mudança desta issue para: ` [FRONT-END] Definição de temas claro/escuro`

Designação das outras demandas para outras issues:

`[FRONT-END] Página de comunidade dinâmica + visualização de perfis de outras pessoas`
`[FRONT-END] Páginas de eventos dinâmica + visualização eventos em formato carrossel`
`[FRONT-END] CRUD Completo de Perfil: Delete e Update`
`[FRONT-END] Estilização da página de perfil, de acordo com o Figma`
`[FRONT-END] Página Home Dinâmica`

Sugestão de adição do seguinte card:

`[FRONT-END] Implementação da funcionalidade de câmera.`

**Comment by lrgsouza** [comment]
@airtong Cards separados de acordo com as atividades.

**Comment by airtong** [comment]
Por enquanto a a barra do top está com a cor definida: #28 

Vou fazer alguns testes manuais com os temas claro/escuro. Acho que vou mexer ainda nas cores do app.

Uma coisa que pretendo modificar é o favicon. No momento está apenas o icone branco.

Como ainda vou modificar isso, mantenho o card em on hold. Devo voltar nisso na próxima sprint.

**Comment by airtong** [comment]
Mais algumas modificações foram feitas nos primeiros commit da pr #29.
Creio que o resultado está satisfatório, até o momento. Vou passar esse card para done.
