### ISSUE TITLE
[FRONT-END] Página de comunidade dinâmica + visualização de perfis de outras pessoas

### ISSUE THREAD

**Issue by lrgsouza** [S204-Inatel-2023-2/binaryhorizon_eventhis_front#19]
@airtong detalhar as atividades a serem realizadas.

**Comment by airtong** [comment]
Isso vai ficar para a próxima sprint.

**Comment by airtong** [comment]
Para a lista de pessoas e/ou amigos:
Implementar um sistema de sliding (https://ionicframework.com/docs/api/item-sliding) para mostrar opções de adicionar e remover amizade.

**Comment by airtong** [comment]
Opções de adicionar amigo ficarão para uma próxima sprint.
Até o momento as páginas estão dinâmicas e já é possível ver perfis de outras pessoas.

**Comment by airtong** [comment]
Possível ver os detalhes na PR https://github.com/S204-Inatel-2023-2/binaryhorizon_eventhis_front/pull/37
