### ISSUE TITLE
[FRONT-END] Páginas de eventos dinâmica

### ISSUE THREAD

**Issue by lrgsouza** [S204-Inatel-2023-2/binaryhorizon_eventhis_front#20]
@airtong detalhar as tarefas a serem realizadas.

**Comment by airtong** [comment]
Conforme definido recentemente, agora a página de eventos será infinita, não mais em formato carrossel.

**Comment by airtong** [comment]
A implementação das páginas foi feita na pr #29.
Enquanto a PR não é aprovada, vou mandar em Code Review. Após a revisão, encaminharei a Testing

**Comment by airtong** [comment]
Passando esse issue para onde holding pois vou implementar o sistema de infinite scrolling na tela /events, mas não é uma prioridade.

Referência: https://ionicframework.com/docs/api/infinite-scroll

**Comment by airtong** [comment]
Quando for ser realizada a implementação de rolagem infinita, haverá outro card. Chamado encerrado, por ora
