### ISSUE TITLE
[FRONT-END] Implementação da funcionalidade de câmera.

### ISSUE THREAD

**Issue by lrgsouza** [S204-Inatel-2023-2/binaryhorizon_eventhis_front#24]
Implementar funcionalidade de camera na aplicação. Tirar ou carregar foto;

**Comment by airtong** [comment]
Funcionalidade implementada em https://github.com/S204-Inatel-2023-2/binaryhorizon_eventhis_front/pull/25.

@EduCR03 se atentar a essa nova funcionalidade, nos testes de register e profile.

**Comment by airtong** [comment]
Atualizações feitas pelo @lrgsouza na PR #29.
